openapi: 3.0.2
servers:
  - url: 'http://127.0.0.1:9000'
    description: Local development
    variables: {}
info:
  description: You should definitely edit this YAML file to get all the tests passing.
  version: 1.0.0
  title: Tutorial for OpenAPI 3 + Connexion + AioHTTP
  termsOfService: ''
  contact:
    email: bradley.belyeu@life.church
    name: Brad Belyeu
tags: []

paths:
  /:
    get:
      summary: Root path
      description: Basic getting started info
      x-openapi-router-controller: handlers
      operationId: root.collection_get
      responses:
        '301':
          description: >-
            This is a permanent redirect to the Github landing page & README. This is primarily
            used just to have a default endpoint to test getting the app running.
  /hello-world:
    get:
      summary: Hello World endpoint
      description: Do that Hello World thang
      x-openapi-router-controller: handlers
      operationId: hello_world.collection_get
      responses:
        '200':
          description: Just return Hello World

  /kudos:
    get:
      summary: Kudos collection endpoint
      description: Use this route to get all kudos in a list
      x-openapi-router-controller: handlers
      operationId: kudos.collection_get
      responses:
        '200':
          description: This is a successful GET request returning a list of Kudo object.
          content:
            application/json:
              schema:
                description: Array of kudo objects.
                type: array
                items:
                  $ref: '#/components/schemas/Kudo'
    post:
      summary: Kudos collection create endpoint
      description: Use this route and POST to create a kudo
      x-openapi-router-controller: handlers
      operationId: kudos.collection_post
      responses:
        '201':
          description: Post a kudo and get the full kudo body back
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kudo'

components:
  schemas:
    Kudo:
      properties:
        id:
          description: Unique identifier
          format: int32
          readOnly: true
          type: integer
        kudo:
          description: Kudo text
          type: string
        created_dt:
          description: This is the date when the kudo was first created.
          format: date-time
          readOnly: true
          type: string
        updated_dt:
          description: This is the date when the kudo was last updated.
          format: date-time
          readOnly: true
          type: string
  requestBodies: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
security: []
