components:
  callbacks: {}
  links: {}
  parameters:
    id:
      description: Kudo Id in the URL
      in: path
      name: id
      required: true
      schema:
        format: int32
        type: integer
  requestBodies: {}
  schemas:
    Kudo:
      properties:
        created_dt:
          description: This is the date when the kudo was first created.
          format: date-time
          readOnly: true
          type: string
        id:
          description: Unique identifier
          format: int32
          readOnly: true
          type: integer
        kudo:
          description: Kudo text
          type: string
        updated_dt:
          description: This is the date when the kudo was last updated.
          format: date-time
          readOnly: true
          type: string
  securitySchemes: {}
info:
  contact:
    email: bradley.belyeu@life.church
    name: Brad Belyeu
  description: You should definitely edit this YAML file to get all the tests passing.
  termsOfService: ''
  title: Tutorial for OpenAPI 3 + Connexion + AioHTTP
  version: 1.0.0
openapi: 3.0.2
paths:
  /:
    get:
      description: Basic getting started info
      operationId: root.collection_get
      responses:
        '301':
          description: This is a permanent redirect to the Github landing page & README.
            This is primarily used just to have a default endpoint to test getting
            the app running.
      summary: Root path
      x-openapi-router-controller: handlers
  /hello-world:
    get:
      description: Do that Hello World thang
      operationId: hello_world.collection_get
      responses:
        '200':
          description: Just return Hello World
      summary: Hello World endpoint
      x-openapi-router-controller: handlers
  /kudos:
    get:
      description: Use this route to get all kudos in a list
      operationId: kudos.collection_get
      responses:
        '200':
          content:
            application/json:
              schema:
                description: Array of kudo objects.
                items:
                  properties:
                    created_dt:
                      description: This is the date when the kudo was first created.
                      format: date-time
                      readOnly: true
                      type: string
                    id:
                      description: Unique identifier
                      format: int32
                      readOnly: true
                      type: integer
                    kudo:
                      description: Kudo text
                      type: string
                    updated_dt:
                      description: This is the date when the kudo was last updated.
                      format: date-time
                      readOnly: true
                      type: string
                type: array
          description: This is a successful GET request returning a list of Kudo object.
      summary: Kudos collection endpoint
      x-openapi-router-controller: handlers
    post:
      description: Use this route and POST to create a kudo
      operationId: kudos.collection_post
      responses:
        '201':
          content:
            application/json:
              schema:
                properties:
                  created_dt:
                    description: This is the date when the kudo was first created.
                    format: date-time
                    readOnly: true
                    type: string
                  id:
                    description: Unique identifier
                    format: int32
                    readOnly: true
                    type: integer
                  kudo:
                    description: Kudo text
                    type: string
                  updated_dt:
                    description: This is the date when the kudo was last updated.
                    format: date-time
                    readOnly: true
                    type: string
          description: Post a kudo and get the full kudo body back
      summary: Kudos collection create endpoint
      x-openapi-router-controller: handlers
  /kudos/{id}:
    get:
      description: Use this route to get a single kudo resource
      operationId: kudos.resource_get
      parameters:
      - description: Kudo Id in the URL
        in: path
        name: id
        required: true
        schema:
          format: int32
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  created_dt:
                    description: This is the date when the kudo was first created.
                    format: date-time
                    readOnly: true
                    type: string
                  id:
                    description: Unique identifier
                    format: int32
                    readOnly: true
                    type: integer
                  kudo:
                    description: Kudo text
                    type: string
                  updated_dt:
                    description: This is the date when the kudo was last updated.
                    format: date-time
                    readOnly: true
                    type: string
          description: This is a successful GET request a single Kudo object.
      summary: Kudo resource read endpoint
      x-openapi-router-controller: handlers
security: []
servers:
- description: Local development
  url: http://127.0.0.1:9000
  variables: {}
tags: []
